require_relative '../node_modules/react-native-test-app/macos/test_app'

workspace 'RNAppleAuthExample.xcworkspace'

# Take advantage of post-install hook to enable ccache
def post_install_hook(installer)
  Pod::UI.puts "Custom post-install hook: Altering build settings to use ccache".yellow
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Using the un-qualified names means you can swap in different implementations, for example ccache
      config.build_settings["CC"] = "clang"
      config.build_settings["LD"] = "clang"
      config.build_settings["CXX"] = "clang++"
      config.build_settings["LDPLUSPLUS"] = "clang++"
    end
  end
end

options = {
  post_install: -> (installer) { post_install_hook(installer) },
#   # :fabric_enabled => false,
  :hermes_enabled => false,
}

use_test_app! options
