name: 'PR Title is Conventional'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        with:
          validateSingleCommit: true
